version: '3'

services:
  mongo:
    image: mongo:latest
    command: mongod --storageEngine wiredTiger
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: swipe4rights
      MONGO_INITDB_ROOT_PASSWORD: password
  python:
    build:
      context: ./
      dockerfile: Dockerfile-python
    command: sh -c "pipenv run /opt/app/manage.py migrate && pipenv run /opt/app/manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    volumes:
      - ./:/opt/app/
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - DOCKER=1
