# Generated by Django 2.0.4 on 2019-07-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=32, unique=True, verbose_name='bill_id')),
                ('supports', models.BooleanField(default=False)),
            ],
        ),
    ]
